Add base survey questions
The-Percentage-Project/survey-engine pull request #36
Opened 2020-10-07 22:28 UTC by megpaik

2020-10-07 22:36 UTC, megpaik commented on common/schema.js
> +// TODO: make this a function that can take custom params
I wasn't sure what this meant, lmk if I should be doing something else with these q's!

2020-10-09 00:53 UTC, gfting requested changes
Note that `[String]` means it's anticipating an array of strings rather than a single `String` in the case of a radio component. Also, I'm not convinced that making things "q1" and "q2" is correct, as it'll make reordering inflexible in the future.

2020-10-09 18:44 UTC, megpaik commented
updated Radio types. Can you clarify your concern with the id naming? My understanding was that the id would simply serve as a unique identifier - how does this affect ordering?

2020-10-10 15:53 UTC, gfting commented
> updated Radio types. Can you clarify your concern with the id naming? My understanding was that the id would simply serve as a unique identifier - how does this affect ordering?

Thanks. What I was thinking is that it's inflexible for the future–consider that new questions get added, or there's a new numbering. In that scenario, the numbers for `q${i}` would no longer be accurate.

2020-10-11 15:37 UTC, gfting approved these changes

2020-10-11 15:37 UTC, merged