WIP sending emails as bg
The-Percentage-Project/survey-engine pull request #70
Opened 2020-11-16 07:18 UTC by Lynx1820

2020-11-16 23:39 UTC, megpaik requested changes
Two main requests: isolating logic into the job and removing the batching logic. Pls lmk once it's ready for another look!

2020-11-16 23:39 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +        const emails = await Email.find({ school, status: requestType });
broad comment, everything that happens in this block besides queuing the job/handling errors should live inside the job. This way, this route is only responsible for parsing the request params and enqueueing the job, and the hairy details (reading from db & calling ses) is isolated in the job itself.

2020-11-16 23:39 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +        const chunkedDecryptedEmails = chunkArray(decryptedEmails, 2);
we can get rid of this and the loop below - we don't need to batch now that we don't need to worry about request timeouts, we just want to add a delay between each email.

2020-11-16 23:39 UTC, megpaik commented on server/src/routes/emailRoutes.js
>          for (let index = 0; index < chunkedDecryptedEmails.length; index++) {
can get rid of this

2020-11-16 23:39 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +function sendMail(emails, senderEmail, requestType, school){
nit: `sendEmail` instead of `sendMail`

2020-11-16 23:39 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +            sendMailQueue.process(async job => {
should this be outside of this request/doesn't doing this cause request timeouts since we're awaiting on all the email sending to complete? i don't think we should be processing the queue in the request lifecycle

2020-11-16 23:39 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +    return new Promise.all(emails.map((email) => {
should this be `await`? 
Also, once you refactor the job to to process all emails, I think you need to add a delay between each in this function instead of using bull's delay option, like what we are doing here: https://github.com/The-Percentage-Project/survey-engine/pull/64/commits/63d3a200850dd9373cc352228beff46e2042d604#diff-cce14d89d0608d03d5df4fc4bd507ba0fcdc40ec8b2a11a861afb15a35719d39R167-R187

2020-11-17 07:25 UTC, Lynx1820 commented on server/src/routes/emailRoutes.js
> +            sendMailQueue.process(async job => {
Sorry, I don't think I follow. I think you're talking about line 187, in which case I think the reason I tried to make a different process for each chunk of emails was because of the timeout you mentioned. I think the reason we're awaiting the process to finish is to know whether the job was completed without errors.

2020-11-17 07:30 UTC, Lynx1820 commented on server/src/routes/emailRoutes.js
> +    return new Promise.all(emails.map((email) => {
Adding the timeout, but the await can't be used outside async function.

2020-11-17 22:41 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +    return new Promise.all(emails.map((email) => {
you can add the `async` keyword to make it compile!

2020-11-17 22:41 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +            sendMailQueue.process(async job => {
I'm referring to the entire`sendMailQueue.process..`. Doesn't this mean we are actually processing the job _inside_ this function, which means we are blocking on the request?

2020-11-17 23:02 UTC, megpaik commented on server/src/routes/emailRoutes.js
> +            sendMailQueue.process(async job => {
i.e. here, only adding the job in the request: https://github.com/heroku-examples/node-workers-example/blob/918d46abae1ee9757632d80c760879afd874ebc0/server.js#L19-L24
And the processing happens outside of the requst: https://github.com/heroku-examples/node-workers-example/blob/main/worker.js

2020-11-19 06:38 UTC, merged